# Tab
tabWidth: 2
useTabs: true

semi: true
trailingComma: 'es5'

bracketSpacing: true

singleQuote: true
jsxSingleQuote: true
jsxBracketSameLine: true
arrowParens: 'avoid'

parser: 'babel'



printWidth: 80